version: "3"
services:
  vite_docker:
    image: node:current-alpine3.17
    container_name: todolistRabit
    entrypoint: tail -f

    ports:
      - 8000:8000
    working_dir: /src/app
    volumes:
      - type: bind
        source: ./
        target: /src/app
    tty: true
    stdin_open: true
